# -*- coding: utf-8 -*-
"""Adapter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/140szuBCkzSxShCtA48Mnv39weVzWq3Xy
"""

import json

class LibraryCatalogAdapter:
    @staticmethod
    def adapt(data, data_format):
        if data_format == "json":
            return LibraryCatalogAdapter._adapt_json(data)
        elif data_format == "csv":
            return LibraryCatalogAdapter._adapt_csv(data)
        else:
            raise ValueError("Unsupported data format!")

    @staticmethod
    def _adapt_json(data):
        return json.loads(data)

    @staticmethod
    def _adapt_csv(data):
        books = []
        lines = data.strip().split("\n")
        for line in lines:
            title, author = line.split(",")
            books.append({"title": title.strip(), "author": author.strip()})
        return books


# Test Adapter
if __name__ == "__main__":
    json_data = '[{"title": "Book 1", "author": "Author 1"}, {"title": "Book 2", "author": "Author 2"}]'
    csv_data = "Book 3, Author 3\nBook 4, Author 4"

    adapted_json = LibraryCatalogAdapter.adapt(json_data, "json")
    adapted_csv = LibraryCatalogAdapter.adapt(csv_data, "csv")

    print("Adapted JSON data:", adapted_json)
    print("Adapted CSV data:", adapted_csv)