# -*- coding: utf-8 -*-
"""Facade.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tJ3JT41ZunT7tCGkbkhAfUWI3thcRAmF
"""

class LibraryCatalog:
    def __init__(self):
        self.books = []

    def add_book(self, title, author):
        self.books.append({"title": title, "author": author, "borrowed": False})

    def find_book(self, title):
        for book in self.books:
            if book["title"].lower() == title.lower():
                return book
        return None

    def borrow_book(self, title):
        book = self.find_book(title)
        if book and not book["borrowed"]:
            book["borrowed"] = True
            return f"'{title}' has been borrowed."
        elif book:
            return f"'{title}' is already borrowed."
        return f"'{title}' not found."


class UserManagement:
    def __init__(self):
        self.users = []

    def add_user(self, name):
        self.users.append({"name": name})

    def list_users(self):
        return [user["name"] for user in self.users]


class LibraryInterface:
    def __init__(self):
        self.catalog = LibraryCatalog()
        self.user_management = UserManagement()

    def add_book(self, title, author):
        self.catalog.add_book(title, author)
        return f"Book '{title}' by {author} added to the catalog."

    def borrow_book(self, title):
        return self.catalog.borrow_book(title)

    def add_user(self, name):
        self.user_management.add_user(name)
        return f"User '{name}' added."

    def list_users(self):
        return self.user_management.list_users()

    def list_books(self):
        return self.catalog.books


# Test Fasady
if __name__ == "__main__":
    library = LibraryInterface()

    # Adding users
    print(library.add_user("John"))
    print(library.add_user("Doe"))

    # Adding books
    print(library.add_book("Cool Book", "Smith XYZ"))
    print(library.add_book("Fun Story", "Jane ABC"))

    # Listing users
    print("Users:", library.list_users())

    # Listing books
    print("Books:", library.list_books())

    # Borrowing books
    print(library.borrow_book("Cool Book"))
    print(library.borrow_book("Cool Book"))
    print(library.borrow_book("Unknown Book"))