# -*- coding: utf-8 -*-
"""Factory.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15AyWYvyegu3yusNSd-QmfvlYlgI11mep
"""

class User:
    def __init__(self, name):
        self.name = name

    def get_permissions(self):
        return "No permissions to borrow books"


class Student(User):
    def get_permissions(self):
        return "Can borrow up to 3 books"


class Teacher(User):
    def get_permissions(self):
        return "Can borrow up to 7 books"


class Librarian(User):
    def get_permissions(self):
        return "Unlimited access to borrowing books"


class UserFactory:
    @staticmethod
    def create_user(user_type, name):
        if user_type == "Student":
            return Student(name)
        elif user_type == "Teacher":
            return Teacher(name)
        elif user_type == "Librarian":
            return Librarian(name)
        else:
            return User(name)


if __name__ == "__main__":

    user1 = UserFactory.create_user("Student", "Michael")
    user2 = UserFactory.create_user("Teacher", "Marcin")
    user3 = UserFactory.create_user("Librarian", "Marcel")
    user4 = UserFactory.create_user("Guest", "Marta")

    print(f"{user1.name}: {user1.get_permissions()}")
    print(f"{user2.name}: {user2.get_permissions()}")
    print(f"{user3.name}: {user3.get_permissions()}")
    print(f"{user4.name}: {user4.get_permissions()}")